[MSHARED-1168] support markup output
apache/maven-reporting-impl pull request #13
Opened 2022-11-27 18:44 UTC by hboutemy

https://issues.apache.org/jira/browse/MSHARED-1168

2022-11-28 19:15 UTC, michael-o requested changes

2022-11-28 19:15 UTC, michael-o commented on pom.xml
> +    </dependency>
Aren't these sufficient at runtime?

2022-11-28 19:15 UTC, michael-o commented on src/main/java/org/apache/maven/reporting/AbstractMavenReport.java
> +        getLog().info( "rendering to " + outputFormat + " markup" );
Rendering...

2022-11-28 19:15 UTC, michael-o commented on src/main/java/org/apache/maven/reporting/AbstractMavenReport.java
> +                throw new MojoExecutionException( "Cannot create sink to " + outputDirectory, ioe );
sink for

2022-11-28 19:15 UTC, michael-o commented on src/main/java/org/apache/maven/reporting/AbstractMavenReport.java
> +        if ( getSink() != null )
When can the sink be `null`?

2022-12-11 16:02 UTC, hboutemy commented on src/main/java/org/apache/maven/reporting/AbstractMavenReport.java
> +        if ( getSink() != null )
just remove this test and you'll see :)
honestly, perhaps it's just unit-test, not real world, adding the code was easier than going more in depth...

2022-12-11 16:02 UTC, hboutemy commented on pom.xml
> +    </dependency>
sadly no

2023-01-31 00:08 UTC, hboutemy commented on src/main/java/org/apache/maven/reporting/AbstractMavenReport.java
> +                throw new MojoExecutionException( "Cannot create sink to " + outputDirectory, ioe );
no, sink to a file in a directory, not for a report

2023-01-31 00:09 UTC, hboutemy commented on src/main/java/org/apache/maven/reporting/AbstractMavenReport.java
> +    @Parameter( property = "output.format" )
I don't know if we should call it `reporting.format` instead...

2023-01-31 15:29 UTC, michael-o commented on src/main/java/org/apache/maven/reporting/AbstractMavenReport.java
> +    @Parameter( property = "output.format" )
`reporting.ouputFormat` since input format is implied.

2023-01-31 15:31 UTC, michael-o requested changes

2023-01-31 15:31 UTC, michael-o commented on src/main/java/org/apache/maven/reporting/AbstractMavenReport.java
> +            generate( sink, sinkFactory, locale );
Attention: This needs to be rebased.

2023-01-31 15:31 UTC, michael-o commented on src/main/java/org/apache/maven/reporting/AbstractMavenReport.java
> +                    + new File( outputDirectory, getOutputName() + '.' + outputFormat ), ioe );
Output format does not necessarily correspond to the output extension.

2023-02-07 20:02 UTC, michael-o commented
@hboutemy Can you address the outstanding discussions? I'd like to release within a week or so.

2023-02-11 15:16 UTC, michael-o approved these changes
LGTM

2023-02-11 19:40 UTC, merged